name: Python Lint

on:
  push:
    paths: ["**.py"]
  pull_request:
    paths: ["**.py"]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: 🔍 Run linter (ruff)
        run: |
          ruff check .

      - name: Check formatting with black
        run: |
          pip install black
          black . --check
